spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: ['metrics', 'prometheus']
---
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-index.html