spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus

  prometheus:
    metrics:
      export:
        enabled: true
---
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-index.html